repos:
  - repo: https://github.com/pycqa/flake8
    rev: "latest"
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "latest"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
